[GHT]
DataPath=./modules/texts/ztext/sample/
ModDrv=zText
CompressType=ZIP
BlockType=Book
SourceType=OSIS
CipherKey=GrantedToPublicDomain
Version=1.0
SwordVersionDate 2026-05-12
History_1.0=Initial module release
Category=Biblical Texts
Lang=en
Encoding=UTF-8
Description=Garth's Hyper-literal Translation
About="Accuracy at the expense of proper English" \par Setting a new bar for "form"al equivalence to the original Greek text by sacrificing easy-readability. It is for serious students of Scripture who want greater transparency into the Greek text. 
DistributionLicense=Public Domain
TextSource=https://www.wiebefamily.org/GHT.htm
